version: '3'

#NETWORK
networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: Server
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - app-network

  frontend:
    container_name: Client
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - app-network
