export const ALL_DOCTOR_REQUEST = 'ALL_DOCTOR_REQUEST'
export const ALL_DOCTOR_SUCCESS = 'ALL_DOCTOR_SUCCESS'
export const ALL_DOCTOR_FAIL = 'ALL_DOCTOR_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'