export const RECORD_LIST_REQUEST = 'RECORD_LIST_REQUEST'
export const RECORD_LIST_SUCCESS = 'RECORD_LIST_SUCCESS'
export const RECORD_LIST_FAIL = 'RECORD_LIST_FAIL'

export const RECORD_DETAILS_REQUEST = 'RECORD_DETAILS_REQUEST'
export const RECORD_DETAILS_SUCCESS = 'RECORD_DETAILS_SUCCESS'
export const RECORD_DETAILS_FAIL = 'RECORD_DETAILS_FAIL'

export const NEW_RECORD_REQUEST = 'NEW_RECORD_REQUEST'
export const NEW_RECORD_SUCCESS = 'NEW_RECORD_SUCCESS'
export const NEW_RECORD_RESET = 'NEW_RECORD_RESET'

export const UPDATE_RECORD_REQUEST = 'UPDATE_RECORD_REQUEST'
export const UPDATE_RECORD_SUCCESS = 'UPDATE_RECORD_SUCCESS'
export const UPDATE_RECORD_RESET = 'UPDATE_RECORD_RESET'

export const DELETE_RECORD_REQUEST = 'DELETE_RECORD_REQUEST'
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS'
export const DELETE_RECORD_RESET = 'DELETE_RECORD_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'